spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/test-LTE-labs"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: almasuj1998

  #    url: ${DB_URL}
  #    driver-class-name: ${DB_DRIVER}
  #    username: ${DB_USERNAME}
  #    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        format-sql: true
server:
  port: 9595
  servlet:
    context-path: /api
